#------------------ Student -----------------
### Get list of Students
GET http://localhost:3200/student
Content-Type: application/json

### Add new student
POST http://localhost:3200/student
Content-Type: application/json

{
    "fullName" : "Dinesh Kumar",
    "age": 25,
    "gender": "M"
}


#------------------ Instructor -----------------
### Get list of Instructors
GET http://localhost:3200/instructor
Content-Type: application/json