#------------------ Student -----------------
### Get list of Students
GET http://localhost:3200/student/
Content-Type: application/json

### Add new student
POST http://localhost:3200/student
Content-Type: application/json

{
    "fullName" : "Gemini Ganesh",
    "age": 32,
    "gender": "M",
    "email": "ganeshGemini@gmail.com"
}

### Update Student Name
PUT http://localhost:3200/student/2
Content-Type: application/json

{
    "fullName" : "James"
}

### Delete exisiting Student
DELETE http://localhost:3200/student/1
Content-Type: application/json



#------------------ Instructor -----------------
### Get list of Instructors
GET http://localhost:3200/instructor
Content-Type: application/json


### Add new instructor
POST http://localhost:3200/instructor
Content-Type: application/json

{
    "fullName" : "Subramanyam",
    "email": "subramanyam@techvedika.com",
    "gender": "M"
}

###  Update Exsisting instructor name
PUT http://localhost:3200/instructor/5
Content-Type: application/json

{
    "fullName" : "Subrmanayam Ayer"
}


### Delete exisiting Instructor
DELETE http://localhost:3200/instructor/1
Content-Type: application/json
