### Fetch All tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new Task
POST http://localhost:3200/tasks
Content-Type: application/json

{
    "title": "Heloooo",
    "date": "2023-11-22T12:11:00Z",
    "description": "Helloooooooooooooooooo licabo",
    "priority": "HIGH",
    "status": "TO DO"
}

### Update Task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
    "id": "f229d842-650c-47f8-9042-e619322c6181",
    "status": "IN PROGRESS"
}

### Delete the Task
DELETE http://localhost:3200/tasks/f229d842-650c-47f8-9042-e619322c6181
Content-Type: application/json
