###
# API-1 Get All todo's
GET http://localhost:3003/todos/?status=TO%20DO

###
# API-2 Get todo
GET http://localhost:3003/todos/5

###
#API -3 Add todo
POST http://localhost:3003/todos
Content-Type: application/json

{
  "todo": "Learn TypeORM Completely",
  "priority": "HIGH",
  "status": "TO DO"
}

###
#API-4 Update todo
PUT http://localhost:8080/todos/1
Content-Type: application/json

{
  "status": "DONE",
  "priority": "MEDIUM"
}

###

# API-5 Get todo
DELETE http://localhost:8080/todos/10
